#!/bin/bash

# magick gif1.gif gif2.gif gif3.gif gif4.gif gif_unido.gif

# Lista los GIFs que quieres unir en este orden
gifs=(
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_01.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_02.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_01.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_02.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_03.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_01.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_01.gif" 
    "adjutora_03.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_02.gif" 
    "adjutora_01.gif"
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_00.gif" 
    "adjutora_small.gif" 
)

# Ejecuta magick con todos los archivos y genera gif_unido.gif
magick "${gifs[@]}" gif_unido.gif
